### ISSUE TITLE
Fix Twitter feed in sidebar

### ISSUE THREAD

**Issue by oalders** [perladvent/perldotcom#344]
Something like this may work:

https://publish.twitter.com/?maxheight=423&maxwidth=465&query=twitter.com%2Fperlfoundation&theme=dark&widget=Timeline

**Comment by davorg** [comment]
Is this still relevant? It looks to me like the Twitter feed is working

**Comment by oalders** [comment]
I think Twitter briefly turned off this endpoint for people who were not logged in. It appears to be working again. The bigger issue now is that TPRF isn't really sending a lot of tweets, so it gives the impression that nothing is happening. We can close this for now, though.
