### ISSUE TITLE
Need a feed url

### ISSUE THREAD

**Issue by matthewpersico** [perladvent/perldotcom#358]
I want to add https://www.perl.com/article/what-s-new-on-cpan-november-2023/ to https://github.com/matthewpersico/planetperl/edit/add-whats-new/perlanetrc. Is there a feed url and a web url that is always the latest one that doens't change? Can you make them?

**Comment by oalders** [comment]
It looks like there is https://www.perl.com/article/index.xml, but the description is massive. Is this workable for now?

**Comment by matthewpersico** [comment]
Looks like perl.com is already on the [list](https://github.com/PerlToolsTeam/planetperl/blob/115c821d591e82297796839ce02b4587cb6c2b86/perlanetrc#L24). Let's see what happens when you post What's New on CPAN - February 2024. When do you think you'll post that one?

**Comment by oalders** [comment]
Those are being created by @matstar2, but I don't have a timeline on the next one. Whenever it's ready, I'm happy to publish it right away.

**Comment by oalders** [comment]
I think I should have updated the publish date when I built the site. I guess they're probably being shown in order in the feed, so probably most people would not have seen them.

**Comment by matstar2** [comment]
January's What's New is coming soon...
