### ISSUE TITLE
Add a "canonical" link to posts

### ISSUE THREAD

**Issue by davorg** [perladvent/perldotcom#387]
Reposting articles from other sites (like my Perl Hacks blog posts) can have a detrimental effect on SEO for both sites. Google sees the same text appearing on different pages and assumes you're gaming the system. The solution is to add a `<link rel="canonical" href="...">` element to the page header.

It looks like you're adding canonical elements to the "authors", "tags" and "categories" pages (and they also appear on some of the really old content) but they're not being added to new articles.

[This blog post](https://discourse.gohugo.io/t/how-to-add-cannonical-url-to-a-blog/34670) shows how to add the element to Hugo pages. In this solution, the value set in the front matter for the article. If the value isn't found, then the URL of the article is used (effectively saying "this is the canonical version of this article").

If you think this is a good idea, then I'll look at editing our templates to add this feature.

**Comment by oalders** [comment]
This is a great idea. ❤️

**Comment by davorg** [comment]
Fixed in https://github.com/perladvent/perldotcom/pull/388
